default['scp_commerce']['903'] = {
  'sitecore' => {
    'package_config_zip_path' => 'c:/tmp/sitecore/SIF.Sitecore.Commerce.1.4.7.zip',
    'package_config_path' => 'c:/tmp/sitecore/SIF.Sitecore.Commerce.1.4.7',
    'package_bizfx_zip_path' => 'c:/tmp/sitecore/Sitecore.BizFX.1.4.1.zip',
    'package_bizfx_path' => 'c:/tmp/sitecore/Sitecore.BizFX.1.4.1',
    'package_sdk_zip_path' => 'c:/tmp/sitecore/Sitecore.Commerce.Engine.SDK.2.4.43.zip',
    'package_sdk_path' => 'c:/tmp/sitecore/Sitecore.Commerce.Engine.SDK.2.4.43',
    'package_zip_path' => 'c:/tmp/Sitecore.Commerce.2018.12-2.4.63.zip',
    'package_url' => 'https://dev.sitecore.net/~/media/A201561B13DE4FC59DE9969812D79322.ashx',
    'package_sxa_zip_path' => 'c:/tmp/sitecore/Sitecore Experience Accelerator 1.8 rev. 181112 for 9.0.zip',
    'package_sxa_url' => 'https://dev.sitecore.net/~/media/2E9624E019FA46B691C9E3851E4A9C2C.ashx',
    'package_spe_zip_path' => 'c:/tmp/sitecore/Sitecore PowerShell Extensions-4.7.2 for Sitecore 8.zip',
    'package_spe_url' => 'https://marketplace.sitecore.net/services/~/media/3D2CADDAB4A34CEFB1CFD3DD86D198D5.ashx?data=Sitecore%20PowerShell%20Extensions-4.7.2%20for%20Sitecore%208&itemId=6aaea046-83af-4ef1-ab91-87f5f9c1aa57',
    'package_nuget_zip_path' => 'c:/tmp/msbuild.microsoft.visualstudio.web.targets.14.0.0.3.nupkg',
    'package_nuget_path' => 'c:/tmp/sitecore/msbuild.microsoft.visualstudio.web.targets.14.0.0.3',
    'package_nuget_url' => 'https://www.nuget.org/api/v2/package/MSBuild.Microsoft.VisualStudio.Web.targets/14.0.0.3',
    'version' => '903',
  },
}
